### PR TITLE
Add DiffusersTextualInversionManager

### PR DESCRIPTION
**Pull request by pdoane**
Support for multi-vector embeddings loaded through the diffusers library

### CODE REVIEW

**Comment by pdoane** [comment]
Adds implementation discussed in #28.  There is an expansion issue addressed in huggingface/diffusers#3188 but I don't think it's worth working around here.

**Comment by damian0815** [comment]
thank you! i'll take a proper look when i get a chance

**Comment by alexisrolland** [comment]
Would be great to merge this! I could use it :)

**Comment by StAlKeR7779** [comment]
I think `DiffusersTextualInversionManager` should be defined in diffusers code.
So that compel gives only abstract part and don't know anything about where it used.
Same done in InvokeAI where class created based on `BaseTextualInversionManager` and compel don't know any about InvokeAI.

**Comment by pdoane** [comment]
> I think DiffusersTextualInversionManager should be defined in diffusers code.

There is a reasonable question for where this should live. InvokeAI is an application and diffusers is a base library so the relationship is a bit different.  There is nothing in diffusers that references Compel (outside of tests).

I was initially planning this as documentation only, but since Compel includes diffusers in requirements.txt it seemed reasonable to include.  I see now that this also only for an example so maybe diffusers should be removed as a dependency here?

**Comment by StAlKeR7779** [comment]
> > I think DiffusersTextualInversionManager should be defined in diffusers code.
> 
> There is a reasonable question for where this should live. InvokeAI is an application and diffusers is a base library so the relationship is a bit different. There is nothing in diffusers that references Compel (outside of tests).
> 
> I was initially planning this as documentation only, but since Compel includes diffusers in requirements.txt it seemed reasonable to include. I see now that this also only for an example so maybe diffusers should be removed as a dependency here?

Now that you said it I'm not sure where it should be :D
It's question like - "diffusers support compel" or "compel support diffusers")
About dependency - as I see that `diffusers` unused and `transformers` used for type annotation.
Maybe it's really should be here as it's based on models defined in `transformers` which... close to `diffusers`.

**Review by damian0815 — APPROVED** [review]

**Comment by pdoane** [comment]
Updated example docs in diffusers here - huggingface/diffusers#3663

**Pull request merged**
